### ISSUE TITLE
NameError: uninitialized constant Gcloud

### ISSUE THREAD

**Issue by md-farhan-memon** [GoogleCloudPlatform/appengine-ruby#8]
I am trying to shift my working Ruby on Rails app to Google App Engine from AWS and have been following guideline [here](https://cloud.google.com/ruby/rails/using-cloudsql-mysql).
I am stuck at _Rails database migrations_ section where when I run `bundle exec rake appengine:exec -- bundle exec rake db:migrate` from my terminal I get the following error.

> rake aborted!
NameError: uninitialized constant Gcloud
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/gems/appengine-0.4.2/lib/appengine/tasks.rb:228:in `rescue in verify_gcloud_and_report_errors'
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/gems/appengine-0.4.2/lib/appengine/tasks.rb:227:in `verify_gcloud_and_report_errors'
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/gems/appengine-0.4.2/lib/appengine/tasks.rb:126:in `block in setup_exec_task'
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
AppEngine::Util::Gcloud::BinaryNotFound: GCloud binary not found in path
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/gems/appengine-0.4.2/lib/appengine/util/gcloud.rb:97:in `binary_path!'
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/gems/appengine-0.4.2/lib/appengine/util/gcloud.rb:143:in `verify!'
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/gems/appengine-0.4.2/lib/appengine/tasks.rb:227:in `verify_gcloud_and_report_errors'
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/gems/appengine-0.4.2/lib/appengine/tasks.rb:126:in `block in setup_exec_task'
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/md_farhan_memon/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => appengine:exec
(See full trace by running task with --trace)

Couldn't find any help on the internet, please suggest something.
Let me know if you need anything else.

**Comment by dazuma** [comment]
The tool is not able to find the `gcloud` binary in your path, which probably means you haven't installed the Google Cloud SDK. It requires the SDK in order to run the migration. You will also need the SDK to deploy to App Engine. Go to https://cloud.google.com/sdk/downloads for instructions on downloading and installing it. If you already installed the SDK, make sure gcloud is in your path when you execute the `bundle exec rake appengine:exec -- bundle exec rake db:migrate` command.

There was supposed to be a helpful error message, but it looks like we botched that. Sorry about that; I'll get it fixed ASAP.

One other thing. Remember to deploy your app first. A version of the application image needs to be in App Engine before you can run the database migration.

**Comment by md-farhan-memon** [comment]
Thanks for the prompt reply @dazuma. I knew it was something related to the sdk.
I have installed the sdk and the app is deployed successfully too, I wanted to run migration.
I have downloaded and extracted the sdk in my _Downloads_  folder and set path in my _bashrc_ like this
`export PATH="~/Downloads/google-cloud-sdk/bin:$PATH"`

Is there any similar way to let know _appengine_ where the _gcloud_ binaries are?

**Comment by dazuma** [comment]
That's odd. A couple other things to check:

* Is gcloud authenticated? I assume it is since you've already deployed to app engine, but maybe do a `gcloud auth list '--format=value(account)'` and see if it returns anything just to be sure.
* Is the project set in your gcloud config? See if `gcloud config get-value project` returns the correct project.

**Comment by md-farhan-memon** [comment]
Both return proper results..first returns my email id I have created the project with and second returns my project id.

**Comment by dazuma** [comment]
I just released version 0.4.3 of the `appengine` gem to fix the issue with displaying the proper error message. Upgrade to that and it should tell you for certain which problem is happening. I expect it's "Could not find the gcloud binary in your system path" but we should be sure.

If that's the case, can you do this:
1. Run `which gcloud` in your shell (the same shell you're trying to run the appengine command from) to make sure it's in the PATH in _that_ shell.
2. Run IRB, and run `system "which gcloud"` to make sure Ruby is picking it up properly. If Ruby can pick it up, then the appengine rake command _should_ pick it up.

**Comment by md-farhan-memon** [comment]
So, the error seems to be same i.e.
> Could not find the `gcloud` binary in your system path.
This tool requires the Google Cloud SDK. To download and install it,
visit https://cloud.google.com/sdk/downloads

However, `which gcloud` returns nothing and `system "which gcloud"` returns `false`.

**Comment by dazuma** [comment]
So gcloud is definitely _not_ in your path in that shell. How are you running `gcloud app deploy` to deploy to app engine? Maybe you need to start a new shell in order to pick up your changes to your bashrc?

In any case, appengine:exec depends on `gcloud` being in the PATH, in the shell from which you're running the rake command. Get to the point where running `which gcloud` in your shell is able to find gcloud, and then things should work.

**Comment by dazuma** [comment]
@md-farhan-memon Are you still having this issue? Were you able to get gcloud into your path?

**Comment by dazuma** [comment]
@md-farhan-memon I'll assume you're not seeing this issue anymore, and I'll close this. Please feel free to reopen if you're still having issues.
